config/routes.rb
Rails.application.routes.draw do
  resources :measurements
  root 'measurements#new'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/measurement.rb
class Measurement < ApplicationRecord
    validates :bust, inclusion: { in: 1..200, message: ": Por favor ingrese un numero de 1 a 200."}
    validates :waist, inclusion: { in: 1..200, message: ": Por favor ingrese un numero de 1 a 200."}
    validates :hip, inclusion: { in: 1..200, message: ": Por favor ingrese un numero de 1 a 200."}
    validates :age, :residence, :birthdate, :cedula, presence: { message: ": Por favor no deje estos campos vacios."}
    # def busto
    #     # 98 102.9  107.8 112.7 117.6
    #     # 98 93.1 88.2 83.3 78.4 73.5
    #     if self.bust >= 98 && self.bust < 102.9
    #             resultado = 0
    #         elsif self.bust > 102.9 && self.bust < 107.8
    #             resultado =  1
    #         elsif self.bust > 107.8 && self.bust < 112.7
    #             resultado = 2
    #         elsif self.bust > 112.7 && self.bust < 117.6
    #             resultado = 3 # positivos
    #         elsif self.bust > 117.6
    #             resultado = 4 # positivos
    #         elsif self.bust < 98 && self.bust > 93.1
    #             resultado = 0 # negativos
    #         elsif self.bust < 93.1 && self.bust > 88.2
    #             resultado = -1

    #         elsif self.bust < 88.2 && self.bust > 83.3
    #             resultado = -2

    #         elsif self.bust < 83.3 && self.bust > 78.4
    #             resultado = -3

    #         elsif self.bust < 78.4 && self.bust > 73.5 || self.bust < 73.5
    #             resultado = -4
    #     end
    # end

    # def cintura
    #     # 80.73 84.77 88.81 92.85 96.89 100.93
    #     # 76.69 72.65 68.61 64.57 60.53 56.49
    #     if self.waist >= 80.73 && self.waist < 84.77
    #             resultado = 0
    #         elsif self.waist > 84.77 && self.waist < 88.81
    #             resultado =  1
    #         elsif self.waist > 88.81 && self.waist < 92.85
    #             resultado = 2
    #         elsif self.waist > 92.85 && self.waist < 96.89
    #             resultado = 3
    #         elsif self.waist > 96.89
    #             resultado = 4 # positivos
    #         elsif self.waist < 80.73 && self.waist > 76.69
    #             resultado = 0 # negativos
    #         elsif self.waist < 76.69 && self.waist > 72.65
    #             resultado = -1

    #         elsif self.waist < 72.65 && self.waist > 68.61
    #             resultado = -2

    #         elsif self.waist < 68.61 && self.waist > 64.57
    #             resultado = -3

    #         elsif self.waist < 64.57 && self.waist > 60.53 || self.waist < 60.53
    #             resultado = -4
    #     end
    # end


    # def cadera
    #     # 104.99 110.24 115.49 120.74 125.99 131.24
    #     # 104.99 99.74 94.49 89.24 83.99 78.74
    #     if self.hip >= 104.99 && self.hip < 110.24
    #             resultado = 0
    #         elsif self.hip > 110.24 && self.hip < 115.49
    #             resultado =  1
    #         elsif self.hip > 115.49 && self.hip < 120.74
    #             resultado = 2
    #         elsif self.hip > 120.74 && self.hip < 125.99
    #             resultado = 3
    #         elsif self.hip > 125.99
    #             resultado = 4 # positivos
    #         elsif self.hip < 104.99 && self.hip > 99.74
    #             resultado = 0 # negativos
    #         elsif self.hip < 99.74 && self.hip > 94.49
    #             resultado = -1

    #         elsif self.hip < 94.49 && self.hip > 89.24
    #             resultado = -2

    #         elsif self.hip < 89.24 && self.hip > 83.99
    #             resultado = -3

    #         elsif self.hip < 83.99 && self.hip > 78.74 || self.hip < 78.74
    #             resultado = -4
    #     end
    # end
    #
    #
    #
    #
    #
    #
    # def busto_medida
    #   ((self.bust - 98) / 4.90)
    # end
    #
    # def cintura_medida
    #   ((self.waist - 80.73) /4.04)
    # end
    #
    # def cadera_medida
    #   ((self.hip - 104.99) / 5.25)
    # end
    #
    # def sum_promedio
    #   (busto_medida() + cintura_medida() + cadera_medida()) / 3
    # end
    #
    # def retornando_busto
    #   rest = (busto_medida() - sum_promedio()).round
    #
    #     if rest <= -1
    #       rest = -1
    #     elsif rest >= 1
    #       rest = 1
    #     else
    #       rest = 0
    #     end
    #
    # end
    #
    # def retornando_cintura
    #   restu = (cintura_medida() - sum_promedio()).round
    #
    #     if restu <= -1
    #       restu = -1
    #     elsif restu >= 1
    #       restu = 1
    #     else
    #       rest = 0
    #     end
    # end
    #
    # def retornando_cadera
    #     restc = (cadera_medida() - sum_promedio()).round
    #
    #     if restc <= -1
    #       restc = -1
    #     elsif restc >= 1
    #       restc = 1
    #     else
    #       rest = 0
    #     end
    # end


    # obtener los flotantes de un numero y sumar el numero entero positivo o negativo
    # def decimal_sum(mi_variable)
    #   if mi_variable > 0
    #     parts = mi_variable.to_s.split(".")
    #     decimal_rest = parts[1].to_i

    #     if decimal_rest > 1 && decimal_rest <= 99
    #       mi_variable.to_i + 1
    #     else
    #       mi_variable.to_i
    #     end
    #   elsif
    #     parts = mi_variable.to_s.split(".")
    #     decimal_rest = parts[1].to_i

    #     if decimal_rest > 1 && decimal_rest <= 99
    #       positivo = mi_variable.to_i * -1
    #       (positivo + 1 ) * -1
    #     else
    #       mi_variable.to_i
    #     end
    #   end
    # end





   ####################################################################################

   def self.busto_medida(busto)
     ((busto - 98) / 4.90)
   end

   def self.cintura_medida(cintura)
     ((cintura - 80.73) /4.04)
   end

   def self.cadera_medida(cadera)
     ((cadera - 104.99) / 5.25)
   end

   def self.sum_promedio(busto,cintura,cadera)
     ((busto + cintura + cadera) / 3)
   end

   def self.retornando_busto(busto,promedio)
     rest = (busto - promedio).round

       if rest <= -1
         rest = -1
       elsif rest >= 1
         rest = 1
       else
         rest = 0
       end

   end

   def self.retornando_cintura(cintura,promedio)
     restu = (cintura - promedio).round

       if restu <= -1
         restu = -1
       elsif restu >= 1
         restu = 1
       else
         rest = 0
       end
   end

   def self.retornando_cadera(cadera,promedio)
       restc = (cadera - promedio).round

       if restc <= -1
         restc = -1
       elsif restc >= 1
         restc = 1
       else
         rest = 0
       end
   end




end

app/controllers/measurements_controller.rb
class MeasurementsController < ApplicationController
  before_action :set_measurement, only: [:show, :edit, :update, :destroy, :show_model_3D]

  # GET /measurements
  # GET /measurements.json
  def index
    @measurement = Measurement.new
    render :new
  end

  # GET /measurements/1
  # GET /measurements/1.json
  def show
    if @measurement.media_body == "[0, 0, 0]" || @measurement.media_body == "[1, 1, 1]"
       @result = 'perla'
    elsif @measurement.media_body == "[0, 0, -1]" || @measurement.media_body == "[1, 0, -1]" || @measurement.media_body == "[1, 0, -2]" || @measurement.media_body == "[1, 1, -1]" || @measurement.media_body == "[1, -1, 1]" || @measurement.media_body == "[1, 1, -2]" || @measurement.media_body == "[2, 0, -2]"
      @result = 'rubí'
    elsif @measurement.media_body == "[0, 0, 1]" || @measurement.media_body == "[-1, 0, 1]" || @measurement.media_body == "[-1, 0, 2]" || @measurement.media_body == "[-1, -1, 1]" || @measurement.media_body == "[0, -1, 2]" || @measurement.media_body == "[-1, -1, 2]" || @measurement.media_body == "[-1, -1, 3]" || @measurement.media_body == "[-1, -2, 2]" || @measurement.media_body == "[2, 0, 1]" || @measurement.media_body == "[-2, 0, 2]"
      @result = 'ámbar'
    elsif @measurement.media_body == "[1, 0, 0]" || @measurement.media_body == "[1, -1, -1]" || @measurement.media_body == "[2, 0, -1]" || @measurement.media_body == "[2, -1, -1]" || @measurement.media_body == "[2, 1, -2]" || @measurement.media_body == "[3, -2, -1]"
      @result ='topacio'
    elsif @measurement.media_body == "[-1, 0, 0]" || @measurement.media_body == "[-1, 1, 1]" || @measurement.media_body == "[-2, 1, 1]"
      @result ='esmeralda'
    elsif @measurement.media_body == "[0, -1, 0]" || @measurement.media_body == "[0, -1, 1]" || @measurement.media_body == "[0, -2, 1]" || @measurement.media_body == "[0, -2, 2]" || @measurement.media_body == "[1, -1, 0]" || @measurement.media_body == "[1, -2, 1]" || @measurement.media_body == "[2, -2, 1]"
      @result ='lapislázuli'
    elsif @measurement.media_body == "[1, 2, -3]" || @measurement.media_body == "[0, 1, 0]" || @measurement.media_body == "[0, 1, -1]" || @measurement.media_body == "[0, 1, -2]" || @measurement.media_body == "[0, 2, -1]" || @measurement.media_body == "[0, 2, -2]" || @measurement.media_body == "[-1, 1, 0]" || @measurement.media_body == "[-1, 1, -1]" || @measurement.media_body == "[-1, 2, 0]" || @measurement.media_body == "[-1, 2, -1]" || @measurement.media_body == "[1, 2, -2]" || @measurement.media_body == "[-1, 2, -2]" ||  @measurement.media_body == "[-1, 3, -2]" || @measurement.media_body == "[-2, 1, 0]" || @measurement.media_body == "[-2, 2, 0]" || @measurement.media_body == "[-2, 2, -1]"
      @result ='amatista'
    else
      @result ='No existe'
    end
  end

  # GET /measurements/new
  def new
    @measurement = Measurement.new
  end

  # GET /measurements/1/edit
  def edit
  end

  # POST /measurements
  # POST /measurements.json
  def create
    @measurement = Measurement.new(measurement_params)

    if @measurement.bust && @measurement.waist && @measurement.hip
      busto = Measurement.busto_medida(@measurement.bust)
      cintura = Measurement.cintura_medida(@measurement.waist)
      cadera = Measurement.cadera_medida(@measurement.hip)

      promedio = Measurement.sum_promedio(busto,cintura,cadera)
      @measurement.media_body =  Measurement.retornando_busto(busto,promedio), Measurement.retornando_cintura(cintura,promedio), Measurement.retornando_cadera(cadera,promedio)
    end

    # def busto_medida
    #   ((@measurement.bust - 98) / 4.90)
    # end
    #
    # def cintura_medida
    #   ((@measurement.waist - 80.73) /4.04)
    # end
    #
    # def cadera_medida
    #   ((@measurement.hip - 104.99) / 5.25)
    # end
    #
    # def sum_promedio
    #   (busto_medida() + cintura_medida() + cadera_medida()) / 3
    # end
    #
    # def retornando_busto
    #   rest = (busto_medida() - sum_promedio()).round
    #
    #     if rest <= -1
    #       rest = -1
    #     elsif rest >= 1
    #       rest = 1
    #     else
    #       rest = 0
    #     end
    #
    # end
    #
    # def retornando_cintura
    #   restu = (cintura_medida() - sum_promedio()).round
    #
    #     if restu <= -1
    #       restu = -1
    #     elsif restu >= 1
    #       restu = 1
    #     else
    #       rest = 0
    #     end
    # end
    #
    # def retornando_cadera
    #     restc = (cadera_medida() - sum_promedio()).round
    #
    #     if restc <= -1
    #       restc = -1
    #     elsif restc >= 1
    #       restc = 1
    #     else
    #       rest = 0
    #     end
    # end
    #
    # @measurement.media_body = retornando_busto().round, retornando_cintura().round, retornando_cadera().round
    puts params[:cedula]
    puts params[:bust]
    respond_to do |format|
      if @measurement.save
        format.html { redirect_to @measurement, notice: 'Measurement was successfully created.' }
        format.json { render :show, status: :created, location: @measurement }
      else
        format.html { render :new }
        format.json { render json: @measurement.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /measurements/1
  # PATCH/PUT /measurements/1.json
  def update
    respond_to do |format|

      if @measurement.update(measurement_params)
        format.html { redirect_to measurements_path, notice: 'Measurement was successfully updated.' }
        format.json { render :show, status: :ok, location: @measurement }
      else
        format.html { render :edit }
        format.json { render json: @measurement.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /measurements/1
  # DELETE /measurements/1.json
  def destroy
    @measurement.destroy
    respond_to do |format|
      format.html { redirect_to measurements_url, notice: 'Measurement was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_measurement
      @measurement = Measurement.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def measurement_params
      params.require(:measurement).permit(:bust, :waist, :hip, :cedula, :media_body, :age, :birthdate, :residence)
    end
end

app/helpers/measurements_helper.rb
module MeasurementsHelper
    
end

app/views/measurements/_form.html.erb
<%= form_with(model: measurement, local: true) do |form| %>
<% if measurement.errors.any? %>
<div class="container row" id="error_explanation">
  <div class="col s12 m7 offset-m2 center-align">
    <ul class="">
      <li class="red-text center-align">*Por favor no deje ningún campo vacio.</li>
    </ul>
  </div>
</div>
<% end %>
<div class="row">
  <div class="col s12 m4">
    <div class="field form">
      <div class="input-field">
        <%= form.label :cedula, "Cedula: ", class:"black-text label" %>
        <%= form.text_field :cedula, id: :cedula , required:true%>
      </div>
    </div>
  </div>
  <div class="col s12 m4">
    <div class="field form">
      <div class="input-field">
        <%= form.label :residence, "Lugar de Residencia: ", class:"black-text label" %>
        <%= form.text_field :residence, id: :residence , required:true%>
      </div>
    </div>
  </div>
  <div class="col s12 m4">
    <div class="field form">
      <div class="input-field">
        <%= form.label :birthdate, "Lugar de Nacimiento: ", class:"black-text label" %>
        <%= form.text_field :birthdate, id: :birthdate , required:true%>
      </div>
    </div>
  </div>

</div>
<div class="row">
<div class="col s12 m3">
  <div class="field form">
    <div class="input-field">
      <%= form.label :age, "Edad: ", class:"black-text label" %>
      <%= form.text_field :age, id: :age , required:true%>
    </div>
    
  </div>
</div>
<div class="col s12 m3">
    <div class="field form">
      <div class="input-field">
        <%= form.label :bust, "Busto: ", class:"black-text label center-align" %> <span id="value"></span>
        <%= form.text_field :bust, id: :measurement_bust, required:true%>
      </div>
    </div>
  </div>
  <div class="col s12 m3">
    <div class="field form">
      <div class="input-field">
        <%= form.label :waist, "Cintura: ", class:"black-text label" %>
        <%= form.text_field :waist, id: :measurement_waist , required:true%>
      </div>
    </div>
  </div>

  <div class="col s12 m3">
    <div class="field form">
      <div class="input-field">
        <%= form.label :hip, "Cadera: ", class:"black-text label" %>
        <%= form.text_field :hip, id: :measurement_hip , required:true%>
      </div>
    </div>
  </div>

</div>







<div class="row">
  <div class="col s12 m6 offset-m3">
    <div class="actions">
      <%= form.submit "Analizar", class:"btn btn-large width-100" %>
    </div>
  </div>
</div>
<% end %>

app/views/measurements/edit.html.erb
<h1>Editing Measurement</h1>

<%= render 'form', measurement: @measurement %>

<%= link_to 'Show', @measurement %> |
<%= link_to 'Back', measurements_path %>

app/views/measurements/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Medidas</h1>

<table class="striped">
  <thead>
    <tr>
      <th>Busto/Media/Acercar</th>
      <th>Cintura/Media/Acercar</th>
      <th>Cadera/Media/Acercar</th>
      <th>Media</th>
      <th colspan="1"></th>
    </tr>
  </thead>
  <tbody>
    <% @measurements.each do |measurement| %>


      <tr>
        <td><%= link_to 'Editar', edit_measurement_path(measurement) %></td>
        <td><%= link_to 'Eliminar', measurement, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Agregar medida', new_measurement_path %>

app/views/measurements/new.html.erb
<div class="container">
<div class="bajar"></div>
<div class="card transparente">
		<div class="card-content">
			<h1 class="title center-align black-text">Medidas</h1>
			<%= render 'form', measurement: @measurement %>
		</div>
	</div>	

	

	
</div>

app/views/measurements/show.html.erb
<div class="row pm-0">
  <div class="col s12 center-align">

    <div class="card">
      <div class="card-image">
       <% if @result == "perla" %>
        <%= video_tag("perla.mp4", preload: true, :autoplay => "autoplay", loop: "", class: 'responsive-video')%>
       <% elsif @result == "amatista" %>
        <%= video_tag("amatista.mp4", preload: true, :autoplay => "autoplay", loop: "", class: 'responsive-video')%>
       <% elsif @result == "rubí" %>
        <%= video_tag("rubi.mp4",  preload: true, :autoplay => "autoplay", loop: "", class: 'responsive-video')%>
       <% elsif @result == "ámbar" %>
        <%= video_tag("ambar.mp4",  preload: true, :autoplay => "autoplay", loop: "", class: 'responsive-video')%>
       <% elsif @result == "topacio" %>
        <%= video_tag("topacio.mp4", preload: true, :autoplay => "autoplay", loop: "", class: 'responsive-video')%>
       <% elsif @result == "esmeralda"%>
       <%= video_tag("esmeralda.mp4", preload: true, :autoplay => "autoplay", loop: "", class: 'responsive-video')%>
        <% elsif @result == "lapislázuli"%>
        <%= video_tag("lapislazuli.mp4", preload: true, :autoplay => "autoplay", loop: "", class: 'responsive-video')%>
       <% end %>
       <span class="card-title">
        <h5 class="title mb-0 black-text"><strong> <%= @result %></strong></h5>
      </span>
    </div>
    <div class="card-content">
      <div class="row">
        <div class="col s12 m4 offset-m2">
        <a href="#modal1" class="btn modal-trigger btn-large width-100"><i class="large material-icons">3d_rotation</i></a>
        </div>
        <div class="col s12 m4">
       
          <%= link_to 'Nueva medida', new_measurement_path, class:"btn btn-large width-100"  %>
            
       
        </div>
      </div>
    </div>
  </div>


</div>
</div>
<div id="modal1" class="modal" tabindex="0">
  <div class="modal-content">
    <div class="video-container">
     <% if @result == "perla" %>

     <iframe src="http://localhost:8000/perla.html"  frameborder="0" width="100%" height="300"></iframe>
     <% elsif @result == "amatista" %>
     <iframe src="http://localhost:8000/amatista.html" frameborder="0" width="100%" height="300"></iframe>
     <% elsif @result == "rubí" %>
     <iframe src="http://localhost:8000/rubi.html" frameborder="0" width="600" height="300"></iframe>
     <% elsif @result == "ámbar" %>
     <iframe src="http://localhost:8000/ambar.html" frameborder="0" width="600" height="300"></iframe>
     <% elsif @result == "topacio" %>
     <iframe src="http://localhost:8000/topacio.html" frameborder="0" width="600" height="300"></iframe>
     <% elsif @result == "esmeralda"%>
     <iframe src="http://localhost:8000/esmeralda.html" frameborder="0" width="600" height="300"></iframe>
     <% elsif @result == "lapislázuli"%>
     <iframe src="http://localhost:8000/lapizlazuli.html" frameborder="0" width="600" height="300"></iframe>
     <% end %>
   </div>



 </div>
</div>